spring:
  profiles:
    active:
    - dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    
beetl:  suffix: html

---
spring:
  profiles: dev
server:
  port: 8080
  servlet:
    context-path: /doc
logging: 
  config: ./config/log4j2.xml      
---
spring:
  profiles: prod
server:
  port: 80
  servlet:
    context-path: /doc
logging: 
  config: ./config/log4j2.xml
        
        